import { GoogleGenAI } from "@google/genai";

const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });

export interface GenerationParams {
  imageData: string; // base64
  mimeType: string;
  profession: string;
  style: string;
  intensity: number;
}

export async function generatePurrfessional(params: GenerationParams): Promise<string> {
  const { imageData, mimeType, profession, style, intensity } = params;

  // Use the default model for image generation and editing
  const model = "gemini-2.5-flash-image";

  let finalBase64 = imageData;
  let finalMimeType = mimeType || "image/jpeg";

  // Handle data URLs (from standard file uploads)
  if (imageData.startsWith('data:')) {
    const match = imageData.match(/^data:([^;]+);base64,(.+)$/);
    if (match) {
      finalMimeType = match[1];
      finalBase64 = match[2];
    }
  } 
  // Handle web URLs (from sample library)
  else if (imageData.startsWith('http')) {
    try {
      const imgResponse = await fetch(imageData);
      const blob = await imgResponse.blob();
      finalMimeType = blob.type;
      finalBase64 = await new Promise((resolve, reject) => {
        const reader = new FileReader();
        reader.onloadend = () => {
          const res = reader.result as string;
          resolve(res.split(',')[1]);
        };
        reader.onerror = reject;
        reader.readAsDataURL(blob);
      });
    } catch (error) {
      console.error("Error fetching library image:", error);
      throw new Error("Failed to process library image. Please try uploading your own photo.");
    }
  }

  const intensityDesc = intensity < 0.3 ? "subtle but clear" : 
                        intensity < 0.7 ? "balanced and noticeable" : 
                        "dramatic and complete";

  const prompt = `Transform this cat into a professional ${profession} in the style of ${style}. 
The transformation should be ${intensityDesc} (intensity level ${intensity} out of 1.0). 
Keep the cat's core likeness but place them in the professional setting with appropriate attire and background. 
If intensity is low, favor the original photo's composition. If intensity is high, fully immerse the cat in the professional role. 
Do not include any human hands or people in the image. The cat should be the sole star.`;

  const response = await ai.models.generateContent({
    model,
    contents: {
      parts: [
        {
          inlineData: {
            data: finalBase64,
            mimeType: finalMimeType,
          },
        },
        {
          text: prompt,
        },
      ],
    },
  });

  // Extract the generated image from the response parts
  if (response.candidates?.[0]?.content?.parts) {
    for (const part of response.candidates[0].content.parts) {
      if (part.inlineData) {
        return `data:image/png;base64,${part.inlineData.data}`;
      }
    }
  }

  throw new Error("No image was generated by the model. Please try again with different settings.");
}
